name: CI/CD для статичного HTML-файлу

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: Github-hosted runners

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ci-cd-html .

      - name: Run Docker container
        run: docker run -d -p 8000:80 ci-cd-html
